= DevTools

include::attribute.adoc[]

English | link:README-zh_CN.adoc[简体中文]

// Plugin description start
image:{jetbrains-plugin-version}[link={jetbrains-plugin-link}]
image:{jetbrains-plugin-downloads}[link={jetbrains-plugin-link}]

image:{github-workflows-badge}[link={github-workflows-link}]
image:{github-forks-badge}[link={github-forks-link}]
image:{github-stars-badge}[link={github-stars-link}]
image:{github-watchers-badge}[link={github-watchers-link}]
image:{github-issues-closed-badge}[link={github-issues-link}]
image:{github-issues-pr-bdage}[link={github-issues-pr-link}]
image:{github-downloads-bdage}[link={github-downloads-link}]
image:{github-code-size-bdage}[]

[[introduce]]
== Introduction

A collection of common development tools for IntelliJ products.

[[features]]
== Features

* Extensions for "Vue.js" plugin
* support rpx or upx pixel unit for Mini Program
* support for Environment configuration file(.env, \*.env, .env.*)

[[install]]
== Installation

* Using IDE built-in plugin system:

- Preferences > Plugins > Browse repositories... > Search for "DevTools" > Install Plugin

* Manually:

- Download the latest release and install it manually using Preferences > Plugins > Install plugin from disk...

// Plugin description end

[[usage]]
== Usage

[[contributing]]
== Contributing image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg[link=https://makeapullrequest.com]

Any type of contribution is welcome, here are some examples of how you may contribute to this project 😃 ：

- Use DevTools in your daily work.
- Submit *{github-issues}[issues]* to report bugs or ask questions.
- Propose *{github-issues-pr}[pull requests]* to improve our code.
